# $pdflatex = "pdflatex -file-line-error -halt-on-error -interaction=nonstopmode -synctex=1";
$pdflatex = "pdflatex -shell-escape -file-line-error -halt-on-error";
$lualatex = "pdflatex -shell-escape -file-line-error -halt-on-error";
$pdf_mode = 4;
